name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Build native XCFramework
        run: |
          cd UsbSerialForMacOS/Native
          ./build-native.sh

      - name: Install .NET workloads
        run: |
          dotnet workload install macos
          dotnet workload install maccatalyst

      - name: Build binding
        run: |
          cd UsbSerialForMacOS
          dotnet build -c Release